import type { ProductionGraph } from "./production";

export function getDemoProduction(): ProductionGraph {
  return {
    productionName: "Coldwater Creek",
    days: [
      {
        id: "day_12",
        date: "2026-09-14",
        type: "day",
        scenes: ["12A", "12B", "12C"],
        location: "Old Mill",
        cast: ["Mara", "Eli", "Jonah"],
        crewSize: 27,
        baseCost: 18400,
        callTime: "06:00",
        wrapTime: "18:00",
        dependencies: ["day_13"],
      },
      {
        id: "day_13",
        date: "2026-09-15",
        type: "night",
        scenes: ["13A", "13B"],
        location: "Old Mill",
        cast: ["Mara", "Jonah"],
        crewSize: 25,
        baseCost: 22900,
        callTime: "16:00",
        wrapTime: "04:00",
        dependencies: ["day_12", "day_18"],
      },
      {
        id: "day_14",
        date: "2026-09-16",
        type: "day",
        scenes: ["14A", "14B", "14C"],
        location: "Riverside Road",
        cast: ["Eli", "Priya"],
        crewSize: 22,
        baseCost: 16100,
        callTime: "07:00",
        wrapTime: "18:00",
        dependencies: ["day_15"],
      },
      {
        id: "day_15",
        date: "2026-09-17",
        type: "day",
        scenes: ["15A"],
        location: "Riverside Road",
        cast: ["Priya", "Jonah"],
        crewSize: 22,
        baseCost: 14200,
        callTime: "07:00",
        wrapTime: "17:00",
        dependencies: ["day_14"],
      },
      {
        id: "day_16",
        date: "2026-09-18",
        type: "night",
        scenes: ["16A", "16B"],
        location: "The Blue Room",
        cast: ["Mara", "Eli"],
        crewSize: 23,
        baseCost: 21100,
        callTime: "15:00",
        wrapTime: "03:00",
        dependencies: [],
      },
      {
        id: "day_17",
        date: "2026-09-19",
        type: "day",
        scenes: ["17A", "17B"],
        location: "County Hospital",
        cast: ["Mara", "Priya"],
        crewSize: 29,
        baseCost: 24500,
        callTime: "06:00",
        wrapTime: "19:00",
        dependencies: ["day_18"],
      },
      {
        id: "day_18",
        date: "2026-09-20",
        type: "night",
        scenes: ["18A", "18B", "18C"],
        location: "Old Mill",
        cast: ["Mara", "Jonah", "Priya"],
        crewSize: 28,
        baseCost: 25800,
        callTime: "16:00",
        wrapTime: "05:00",
        dependencies: ["day_13", "day_17"],
      },
      {
        id: "day_19",
        date: "2026-09-21",
        type: "day",
        scenes: ["19A", "19B"],
        location: "Warehouse District",
        cast: ["Eli", "Jonah"],
        crewSize: 24,
        baseCost: 19800,
        callTime: "07:00",
        wrapTime: "18:00",
        dependencies: [],
      },
      {
        id: "day_20",
        date: "2026-09-22",
        type: "day",
        scenes: ["20A"],
        location: "Warehouse District",
        cast: ["Priya", "Jonah"],
        crewSize: 24,
        baseCost: 15400,
        callTime: "07:00",
        wrapTime: "17:00",
        dependencies: ["day_19"],
      },
      {
        id: "day_21",
        date: "2026-09-23",
        type: "night",
        scenes: ["21A", "21B"],
        location: "Subway Platform",
        cast: ["Mara", "Eli"],
        crewSize: 26,
        baseCost: 23700,
        callTime: "18:00",
        wrapTime: "05:00",
        dependencies: [],
      },
      {
        id: "day_22",
        date: "2026-09-24",
        type: "day",
        scenes: ["22A", "22B"],
        location: "Rooftop",
        cast: ["Mara", "Priya"],
        crewSize: 21,
        baseCost: 17600,
        callTime: "06:00",
        wrapTime: "17:00",
        dependencies: [],
      },
      {
        id: "day_23",
        date: "2026-09-25",
        type: "day",
        scenes: ["23A"],
        location: "Rooftop",
        cast: ["Mara"],
        crewSize: 20,
        baseCost: 13200,
        callTime: "07:00",
        wrapTime: "16:00",
        dependencies: ["day_22"],
      },
    ],
    budgetSummary: {
      totalBudget: 450000,
      spentToDate: 262000,
      remaining: 188000,
      contingencyPct: 8,
      currency: "USD",
    },
  };
}